version: '3.8'

services:
  # IAM Service - Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KC_DB: dev-file
      KEYCLOAK_ADMIN: adminuser
      KEYCLOAK_ADMIN_PASSWORD: CloudPassword123!
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    ports:
      - "8080:8080"
    command: start-dev

  # S3 Storage Service - MinIO
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: MinioPassword123!
    ports:
      - "9000:9000" 
      - "9001:9001" 
    volumes:
      - ./minio_data:/data 
    command: server /data --console-address :9001
